baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Generative AI for Software Engineering (GAISE)'
theme = "paperesque"

[params]
    author = "GAISE Course"
    description = "Course materials and resources for Generative AI for Software Engineering"
